export const START_INITIAL_GET_POST = 'START_INITIAL_GET_POST';
export const INITIAL_GET_POST_SUCCESS = 'INITIAL_GET_POST_SUCCESS';
export const INITIAL_GET_POST_ERROR = 'INITIAL_GET_POST_ERROR';

export const START_GET_A_POST = 'START_GET_A_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const SET_COMMENT_IN_POST = 'SET_COMMENT_IN_POST';
export const COMMENT_IN_POST_SUCCESS = 'COMMENT_IN_POST_SUCCESS';
export const COMMENT_IN_POST_ERROR = 'COMMENT_IN_POST_ERROR';

export const SET_NEW_POST = 'SET_NEW_POST';
export const SET_NEW_POST_SUCCESS = 'SET_NEW_POST_SUCCESS';
export const SET_NEW_POST_ERROR = 'SET_NEW_POST_ERROR';

export const DELETE_POST = 'DELETE_NEW_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const UPDATE_POST_MODAL = 'UPDATE_POST_MODAL';
export const UPDATE_POST_SUCCESS_MODAL = 'UPDATE_POST_SUCCESS_MODAL';
export const UPDATE_POST_ERROR_MODAL = 'UPDATE_POST_ERROR_MODAL';


export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

export const HIDE_MODAL_UPDATE = 'HIDE_MODAL_UPDATE';
