export const START_INITIAL_GET_POST = 'START_INITIAL_GET_POST';
export const INITIAL_GET_POST_SUCCESS = 'INITIAL_GET_POST_SUCCESS';
export const INITIAL_GET_POST_ERROR = 'INITIAL_GET_POST_ERROR';

export const START_GET_A_POST = 'START_GET_A_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const SET_COMMENT_IN_POST = 'SET_COMMENT_IN_POST';
export const COMMENT_IN_POST_SUCCESS = 'COMMENT_IN_POST_SUCCESS';
export const COMMENT_IN_POST_ERROR = 'COMMENT_IN_POST_ERROR';